### ISSUE TITLE
Withdraw-X/Deposit-X Swap not working for me.

### ISSUE THREAD

**Issue by TerminalD** [devinfrench/runelit#1]
Hi @devinfrench great fork! However, I've enabled the bank toggles and the entries aren't swapped. Could you take a look whenever you have time?

Enabled in the menu, and menu entry swapper itself is also enabled.
![enabled_options](https://user-images.githubusercontent.com/40116429/41191146-51344af8-6beb-11e8-8185-e6b8bb7348d8.JPG)
Still says deposit-1 here.
![not_swapped](https://user-images.githubusercontent.com/40116429/41191147-53544734-6beb-11e8-895f-9eeafc081abe.JPG)

Any plans on implementing other features like `hide hidden items` and `volcanic mine`?

Thanks a bunch man!

**Comment by devinfrench** [comment]
Fixed in next release. 

I don't have access to volcanic mine so I won't be adding that anytime soon unless someone else adds it.
For hidden items I am just going to remove the Take option.

**Comment by TerminalD** [comment]
Cool thanks for the quick work! Looking forward to the hiddens item commit :)

**Comment by devinfrench** [comment]
Added in https://github.com/devinfrench/runelit/releases/tag/1.2.1

**Comment by TerminalD** [comment]
Just tested an all works great! Might be better if you'd make the `hide hidden items` a toggleable inside the ground items menu for other people. Just my two cents, not sure if I missed it though.

Thanks for the release!
